# Generated by Django 4.0.1 on 2022-03-02 01:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('contact_email', models.CharField(max_length=40)),
                ('contact_mobile_number', models.PositiveIntegerField()),
                ('site_type', models.CharField(blank=True, default=None, max_length=3, null=True, unique=True)),
            ],
        ),
    ]
