# Generated by Django 4.0.1 on 2022-05-22 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=70)),
                ('lat', models.FloatField(default=None)),
                ('lng', models.FloatField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.address'),
        ),
    ]
