# Generated by Django 4.0.1 on 2022-02-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='site_type',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
