# Generated by Django 4.0.1 on 2022-05-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='site_type',
            field=models.CharField(default=None, max_length=3, null=True),
        ),
    ]
