# Generated by Django 4.0.1 on 2022-05-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_address_alter_building_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='full_address',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
