# Generated by Django 4.0.1 on 2022-03-21 16:31

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_building_code_alter_building_site_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=250)),
                ('pass_building', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'ordering': ['site_name']},
        ),
        migrations.AddField(
            model_name='building',
            name='inspections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.inspection'),
        ),
    ]
