# Generated by Django 4.0.1 on 2022-05-17 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_inspection_site_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='address',
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(default=None, max_length=20, null=True)),
                ('lat', models.CharField(default=None, max_length=20)),
                ('lng', models.CharField(default=None, max_length=20)),
                ('building', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.building')),
            ],
        ),
    ]
