# Generated by Django 4.0.1 on 2022-05-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_remove_building_address_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='full_address',
            field=models.CharField(default=None, max_length=70, null=True),
        ),
    ]
