# Generated by Django 4.0.1 on 2022-04-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_inspection_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='regulation',
            field=models.CharField(default=None, max_length=7, null=True),
        ),
    ]
