# Generated by Django 4.0.1 on 2022-04-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_building_regulation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
