# Generated by Django 4.0.1 on 2022-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_building_address_address_building'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
