# Generated by Django 4.0.1 on 2022-04-16 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_building_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='pass_building',
            new_name='is_pass_building',
        ),
        migrations.RemoveField(
            model_name='building',
            name='inspections',
        ),
    ]
