# Generated by Django 4.0.1 on 2022-05-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_address_lat_alter_address_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='lat',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='lng',
            field=models.FloatField(default=None),
        ),
    ]
