# Generated by Django 4.0.1 on 2022-04-16 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_inspection_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='inspections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.inspection'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
