# Generated by Django 4.0.1 on 2022-04-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_building_inspections_alter_inspection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='is_pass_building',
            field=models.BooleanField(),
        ),
    ]
