# Generated by Django 4.0.1 on 2022-04-16 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_alter_inspection_is_pass_building'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='is_pass_building',
            new_name='is_inspection_successful',
        ),
    ]
