# Generated by Django 4.0.1 on 2022-04-17 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
