# Generated by Django 4.0.1 on 2022-04-17 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_remove_building_inspections_inspection_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='building',
        ),
        migrations.AddField(
            model_name='building',
            name='inspection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.inspection'),
        ),
    ]
