# Generated by Django 4.0.1 on 2022-04-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_remove_building_inspection_inspection_building'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='description',
        ),
    ]
