# Generated by Django 4.0.1 on 2022-04-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_inspection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='description',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
