# Generated by Django 4.0.1 on 2022-04-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_inspection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='is_inspection_successful',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
