# Generated by Django 4.0.1 on 2022-04-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0018_alter_inspection_is_inspection_successful'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='created_by',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AddField(
            model_name='building',
            name='modificated_by',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='inspection',
            name='inspected_by',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
