# Generated by Django 4.0.1 on 2022-04-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_alter_building_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='created_by',
        ),
    ]
