# Generated by Django 4.0.1 on 2022-04-26 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_remove_building_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='modificated_by',
        ),
        migrations.RemoveField(
            model_name='inspection',
            name='inspected_by',
        ),
    ]
