# Generated by Django 4.0.1 on 2022-04-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_building_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='created_by',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
