# Generated by Django 4.0.1 on 2022-04-28 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_building_modificated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='inspected_by',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
