# Generated by Django 4.0.1 on 2022-05-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_inspection_inspected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
