# Generated by Django 4.0.1 on 2022-05-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_alter_inspection_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
